Created grade table
MlcccCodingClass/ChineseCharactersRecognitionApp pull request #57
Opened 2023-10-22 04:56 UTC by magicArc

2023-10-22 14:20 UTC, stoneskin commented
@magicArc  please add MySQL script for inserting row fo grades 1 to 3 to the table. 
see example in the user table and event table example

2023-10-22 23:29 UTC, stoneskin requested changes
Add insert scripts at least 3 rows, default 50 words for each level. 
remove LastVisit change to lastModifed

2023-10-28 01:48 UTC, magicArc commented
@stoneskin I changed the LastVisit to lastModified and added rows for grades 1-3

2023-10-29 01:55 UTC, wsun4ipipeline approved these changes

2023-10-29 01:56 UTC, stoneskin approved these changes

2023-10-29 01:56 UTC, merged