task 64 - get number of words from database and store in cookie
MlcccCodingClass/ChineseCharactersRecognitionApp pull request #72
Opened 2023-11-18 02:07 UTC by esun366

Hi Mr. Sun,

I completed task 64.

Best,
Eric S

2023-11-19 03:06 UTC, stoneskin requested changes
Hi, Eric, 
You did a good job,  but we need more work on this task,
please see my new comments in the task.
Thanks
Mr.Sun

2023-11-25 15:34 UTC, esun366 commented
Hi Mr. Sun,

Thanks for the code review; I updated the code based on the feedback you've given me.

Best,
Eric

2023-12-02 17:43 UTC, wsun4ipipeline approved these changes

2023-12-02 17:48 UTC, stoneskin approved these changes

2023-12-02 17:48 UTC, merged